// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 💡 느낌표(!)를 붙여서 'undefined'가 아님을 단언합니다.
    url: process.env.DATABASE_URL!,
  },
});
