export const genreIcons: Record<string, any> = {
    "defalut": "💿",
    "Pop": "🎤",
    "Hip-Hop": "😎",
    "Rock": "🎸",
    "Dance": "🕺",
    "R&B": "🪔",
    "Alternative": "🛸",
    "Electro": "🕹️",
    "Folk": "🪕",
    "Reggae": "🌴",
    "Jazz": "🎷",
    "Classical": "🎻",
    "OST": "🎬",
    "Metal": "🤘",
    "Soul & Funk": "🎶",
    "African Pop": "🐘",
    "Blues": "🍷",
    "Brazilian Pop": "🇧🇷",
    "Indian Pop": "👳‍♂️",
    "Kids": "🎠",
    "Latin Pop": "💃",
}