import type { Metadata } from "next";
import NextAuthProvider from "./providers";
import SessionGate from "@/components/auth/SessionGate";
import SimpleBottomNavigation from "@/components/common/BottomNavigation";
import ReactQueryProvider from "@/lib/providers/ReactQueryProvider";
import GlobalTrackDialog from "@/components/common/GlobalTrackDialog";
import MainPlayer from "@/components/common/MainPlayer";

import '../styles/_style.scss';

export const metadata: Metadata = {
  title: "Zizi !",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ //안 건드릴 값
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={'antialiased'}
      >
        <ReactQueryProvider>              {/* 서버 데이터 관리 */}
          <NextAuthProvider>              {/* 인증 상태 관리 */}
            <SessionGate>                 {/* 사용자 상태 체크 (추가 정보 필요 시 팝업 띄우고, 아니면 children 렌더링) */}
              {/* 1. 메인 콘텐츠 */}
              {children}

              {/* 2. 전역 재생 플레이어 (하단 네비게이션 위에 떠 있어야 함) */}
              <MainPlayer />

              {/* 3. 하단 네비게이션 */}
              <SimpleBottomNavigation />

              {/* 4. 전역 다이얼로그 (최상위 레이어) */}
              <GlobalTrackDialog />
            </SessionGate>
          </NextAuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
