import type { Metadata } from "next";
import NextAuthProvider from "./providers";
import SessionGate from "@/components/auth/SessionGate";
import SimpleBottomNavigation from "@/components/common/BottomNavigation";
import ReactQueryProvider from "@/lib/providers/ReactQueryProvider";

import '../styles/_style.scss';

export const metadata: Metadata = {
  title: "Zizi !",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ //안 건드릴 값
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={'antialiased'}
      >
        <ReactQueryProvider>              {/* 서버 데이터 관리 */}
          <NextAuthProvider>              {/* 인증 상태 관리 */}
            <SessionGate>                 {/* 사용자 상태 체크 (추가 정보 필요 시 팝업 띄우고, 아니면 children 렌더링) */}
              {children}
              <SimpleBottomNavigation />  {/* 하단 네비게이션 */}
            </SessionGate>
          </NextAuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
